services:
  backend:
    build:
      context: .
      dockerfile: server.dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGO_URL=mongodb://db:27017/tester
      - PORT=4000
      - SECRET_KEY=your_secret_key
    depends_on:
      - db

  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=tester
    volumes:
      - db_data:/data/db

volumes:
  db_data:
    driver: local
