version: "7"

services:
  backend:
    image: ghcr.io/your-username/your-backend-image:latest
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=db://user:password@db:5432/dbname
    depends_on:
      - db
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=test
    ports:
      - "27017:27017"
    volumes:
      - db_data:/var/lib/postgresql/data
